### ISSUE TITLE
OS X - nest2D fork not installing

### ISSUE THREAD

**Issue by BitLox** [EthanRosenthal/nannernest#5]
Boost and cmake were already installed and upgraded via brew

````
player1@SquidBook Experiments % pip install git+https://github.com/EthanRosenthal/nest2D.git@download-dependencies
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting git+https://github.com/EthanRosenthal/nest2D.git@download-dependencies
  Cloning https://github.com/EthanRosenthal/nest2D.git (to revision download-dependencies) to /private/var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/pip-req-build-uUXSsk
  Running command git clone -q https://github.com/EthanRosenthal/nest2D.git /private/var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/pip-req-build-uUXSsk
  Running command git checkout -b download-dependencies --track origin/download-dependencies
  Switched to a new branch 'download-dependencies'
  Branch 'download-dependencies' set up to track remote branch 'download-dependencies' from 'origin'.
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@2/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/pip-req-build-uUXSsk/setup.py'"'"'; __file__='"'"'/private/var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/pip-req-build-uUXSsk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/pip-req-build-uUXSsk/pip-egg-info
         cwd: /private/var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/pip-req-build-uUXSsk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zm/4nmmy__d0n5_m634_w_hm_1w0000gp/T/pip-req-build-uUXSsk/setup.py", line 18, in <module>
        with open(os.path.join(here, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
player1@SquidBook Experiments % 
````

**Comment by EthanRosenthal** [comment]
It looks like you're still using Python 2.7. Sorry, but this package requires Python 3.7+. I should add that to the README!

**Comment by BitLox** [comment]
Odd. I also have python 3.8 installed. Wonder why it’s not using that one.

**Comment by EthanRosenthal** [comment]
This always happens to me if `pip` is not installed in my virtual environment, and I end up defaulting to the system `pip`.

**Comment by BitLox** [comment]
Ah ok, I just tried using pip3 as the install command and it worked fine.
